services:
  backend:
    build:
      context: ./backend

    container_name: ai-sql-analyst-backend

    ports:
      - "8005:8005"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app

    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: ai-sql-analyst-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend